[workspace]
resolver = "2"
members = ["day-*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
anyhow = { version = "1.0.75", features = [] }
rstest = "0.18.2"
regex = "1.10.2"
itertools = "0.12.0"
rangemap = "1.4.0"